# Generated by Django 5.2.14 on 2026-05-08 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VehicleMake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Vehicle Make",
                "verbose_name_plural": "Vehicle Makes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="vehicles.vehiclemake",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Model",
                "verbose_name_plural": "Vehicle Models",
                "ordering": ["name"],
                "unique_together": {("make", "name")},
            },
        ),
        migrations.CreateModel(
            name="Vehicle360Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to apply to all years",
                        max_length=10,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("car", "Car 360° View"), ("part", "Part 360° View")],
                        default="car",
                        max_length=10,
                    ),
                ),
                (
                    "part_slug",
                    models.CharField(
                        blank=True,
                        help_text="e.g. transmissions-for-sale (for part assets only)",
                        max_length=100,
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Upload MP4 360° spin video",
                        null=True,
                        upload_to="360/videos/",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Preview thumbnail image",
                        null=True,
                        upload_to="360/thumbnails/",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Mercedes-Benz AMG GT Coupe 2024",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="vehicles.vehiclemake",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="vehicles.vehiclemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "360° Asset",
                "verbose_name_plural": "360° Assets",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
