# Generated by Django 5.2.14 on 2026-05-10 00:01

import django.db.models.deletion
import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle360asset",
            options={
                "ordering": ["make__name", "model__name", "asset_type", "part_slug"],
                "verbose_name": "360° Asset",
                "verbose_name_plural": "360° Assets",
            },
        ),
        migrations.AlterField(
            model_name="vehicle360asset",
            name="label",
            field=models.CharField(
                blank=True,
                help_text='Friendly label shown on website, e.g. "Toyota Camry 2024"',
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle360asset",
            name="model",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank = applies to ALL models of this make",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="vehicles.vehiclemodel",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle360asset",
            name="part_slug",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— Not applicable (car asset) —"),
                    ("transmissions-for-sale", "Transmissions"),
                    ("engines-for-sale", "Engines"),
                    ("axle-shaft-for-sale", "Axle Shaft"),
                    ("drive-shaft-for-sale", "Drive Shaft"),
                    ("differential-for-sale", "Differential"),
                    ("speedometer-for-sale", "Speedometer"),
                    ("throttle-body-for-sale", "Throttle Body"),
                    ("transfer-case-assembly-for-sale", "Transfer Case Assembly"),
                    (
                        "steering-gear-rack-pinion-for-sale",
                        "Steering Gear Rack & Pinion",
                    ),
                    ("intake-manifold-for-sale", "Intake Manifold"),
                    ("steering-column-for-sale", "Steering Column"),
                    ("spindle-knuckle-for-sale", "Spindle Knuckle"),
                    ("axle-assembly-for-sale", "Axle Assembly"),
                    ("abs-assembly-for-sale", "ABS Assembly"),
                ],
                help_text="Select the website page this part video belongs to (Part assets only)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle360asset",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Optional preview image shown before video loads",
                null=True,
                upload_to=vehicles.models.vehicle_thumb_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle360asset",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload .mp4 360° spin video (max 50 MB recommended)",
                null=True,
                upload_to=vehicles.models.vehicle_video_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle360asset",
            name="year",
            field=models.CharField(
                blank=True,
                help_text="Leave blank = applies to all years",
                max_length=10,
            ),
        ),
    ]
