# Generated by Django 5.2.14 on 2026-06-10 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0002_partpage_asset_360_label_and_more"),
        ("vehicles", "0002_part_slug_choices_smart_upload"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle360asset",
            options={
                "ordering": [
                    "make__name",
                    "model__name",
                    "asset_type",
                    "part_slug",
                    "part_type__label",
                ],
                "verbose_name": "360° Asset",
                "verbose_name_plural": "360° Assets",
            },
        ),
        migrations.AddField(
            model_name="vehicle360asset",
            name="part_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional — select the specific type (e.g. Automatic, V6) this asset belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="parts.parttype",
            ),
        ),
    ]
