# Generated by Django 5.2.14 on 2026-06-10 11:50

import django.db.models.deletion
import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0002_partpage_asset_360_label_and_more"),
        ("vehicles", "0003_add_part_type_fk_to_asset"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarAsset",
            fields=[],
            options={
                "verbose_name": "Car 360° Asset",
                "verbose_name_plural": "Car 360° Assets",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vehicles.vehicle360asset",),
        ),
        migrations.CreateModel(
            name="PartAsset",
            fields=[],
            options={
                "verbose_name": "Part 360° Asset",
                "verbose_name_plural": "Part 360° Assets",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vehicles.vehicle360asset",),
        ),
        migrations.AlterModelOptions(
            name="vehicle360asset",
            options={
                "ordering": [
                    "asset_type",
                    "part_slug",
                    "part_type__label",
                    "make__name",
                    "model__name",
                ],
                "verbose_name": "360° Asset",
                "verbose_name_plural": "360° Assets",
            },
        ),
        migrations.AlterField(
            model_name="vehicle360asset",
            name="label",
            field=models.CharField(
                blank=True,
                help_text='Friendly label, e.g. "Toyota Camry 2024" or "Automatic Transmission"',
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle360asset",
            name="make",
            field=models.ForeignKey(
                blank=True,
                help_text="Required for Car assets. Leave blank for Part assets.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="vehicles.vehiclemake",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle360asset",
            name="part_slug",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— Select Part Page —"),
                    ("transmissions-for-sale", "Transmissions"),
                    ("engines-for-sale", "Engines"),
                    ("axle-shaft-for-sale", "Axle Shaft"),
                    ("drive-shaft-for-sale", "Drive Shaft"),
                    ("differential-for-sale", "Differential"),
                    ("speedometer-for-sale", "Speedometer"),
                    ("throttle-body-for-sale", "Throttle Body"),
                    ("transfer-case-assembly-for-sale", "Transfer Case Assembly"),
                    (
                        "steering-gear-rack-pinion-for-sale",
                        "Steering Gear Rack & Pinion",
                    ),
                    ("intake-manifold-for-sale", "Intake Manifold"),
                    ("steering-column-for-sale", "Steering Column"),
                    ("spindle-knuckle-for-sale", "Spindle Knuckle"),
                    ("axle-assembly-for-sale", "Axle Assembly"),
                    ("abs-assembly-for-sale", "ABS Assembly"),
                ],
                help_text="Which part page does this asset belong to?",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle360asset",
            name="part_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Which type within this part? (e.g. Automatic, V6, Front)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="parts.parttype",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle360asset",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Optional preview thumbnail shown before video plays",
                null=True,
                upload_to=vehicles.models.vehicle_thumb_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle360asset",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload MP4 360° spin video (max 50 MB recommended)",
                null=True,
                upload_to=vehicles.models.vehicle_video_upload_path,
            ),
        ),
    ]
