# Generated by Django 5.1.4 on 2026-06-19 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0004_split_car_part_assets_nullable_make"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="years",
                        to="vehicles.vehiclemake",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="years",
                        to="vehicles.vehiclemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Year",
                "verbose_name_plural": "Vehicle Years",
                "ordering": ["make__name", "model__name", "-year"],
                "unique_together": {("make", "model", "year")},
            },
        ),
    ]
