# Generated by Django 5.2.14 on 2026-05-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("car_make", models.CharField(blank=True, max_length=100)),
                ("car_model", models.CharField(blank=True, max_length=100)),
                ("car_year", models.CharField(blank=True, max_length=10)),
                ("part_type", models.CharField(blank=True, max_length=100)),
                ("source_page", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_contacted", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
