# Generated by Django 5.2.14 on 2026-05-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="part_slug",
            field=models.CharField(
                blank=True, help_text="e.g. transmissions-for-sale", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="part_type",
            field=models.CharField(
                blank=True, help_text="Selected dropdown option", max_length=200
            ),
        ),
    ]
