# Generated by Django 5.2.14 on 2026-05-08 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_lead_part_slug_alter_lead_part_type"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="vehicle_make",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked vehicle make from the database",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="vehicles.vehiclemake",
                verbose_name="Make (FK)",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="vehicle_model",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked vehicle model from the database",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="vehicles.vehiclemodel",
                verbose_name="Model (FK)",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="car_make",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Make (text)"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="car_model",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Model (text)"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="car_year",
            field=models.CharField(blank=True, max_length=10, verbose_name="Year"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Received At"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email Address"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="full_name",
            field=models.CharField(max_length=200, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="is_contacted",
            field=models.BooleanField(default=False, verbose_name="Contacted?"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="part_slug",
            field=models.CharField(
                blank=True,
                help_text="e.g. transmissions-for-sale",
                max_length=100,
                verbose_name="Part Page Slug",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="part_type",
            field=models.CharField(
                blank=True,
                help_text="Selected dropdown option",
                max_length=200,
                verbose_name="Part Type Selected",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(max_length=30, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="source_page",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Source Page"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="Zip Code"),
        ),
    ]
