# Generated by Django 5.2.14 on 2026-05-08 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PartPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("page_title", models.CharField(max_length=200)),
                (
                    "hero_headline",
                    models.TextField(default="Get the Lowest Prices on\nUsed Parts!"),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="Save Up to 50% Off Dealer Prices with Fast Shipping!",
                        max_length=300,
                    ),
                ),
                (
                    "hero_image",
                    models.CharField(default="/images/hero.png", max_length=300),
                ),
                ("product_image", models.CharField(blank=True, max_length=300)),
                ("video_url", models.CharField(blank=True, max_length=300)),
                ("about_text", models.TextField()),
                ("about_extra", models.TextField(blank=True)),
                ("part_type_label", models.CharField(max_length=100)),
                ("part_finder_title", models.TextField()),
                ("benefit_title", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Part Page",
                "verbose_name_plural": "Part Pages",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PackageDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail_text", models.CharField(max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "part_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_details",
                        to="parts.partpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Package Detail",
                "verbose_name_plural": "Package Details",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PartType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "part_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_types",
                        to="parts.partpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Part Type Option",
                "verbose_name_plural": "Part Type Options",
                "ordering": ["order", "label"],
            },
        ),
    ]
