# Generated by Django 5.2.14 on 2026-05-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partpage",
            name="asset_360_label",
            field=models.CharField(
                blank=True,
                help_text="Display label for the 3D view, e.g. 'OEM Automatic Transmission'",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="partpage",
            name="asset_360_thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Preview thumbnail shown before the video plays",
                null=True,
                upload_to="360/parts/thumbnails/",
            ),
        ),
        migrations.AddField(
            model_name="partpage",
            name="asset_360_video",
            field=models.FileField(
                blank=True,
                help_text="Upload an MP4 360° spin video for this part (e.g. transmission spinning)",
                null=True,
                upload_to="360/parts/",
            ),
        ),
        migrations.AlterField(
            model_name="partpage",
            name="video_url",
            field=models.CharField(
                blank=True, help_text="Legacy hero video URL", max_length=300
            ),
        ),
    ]
