# Generated by Django 5.1.4 on 2026-06-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0002_partpage_asset_360_label_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name (e.g., SUZUKI)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display name (e.g., Suzuki)", max_length=100
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Short tagline (e.g., Way of Life!)",
                        max_length=200,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#000000",
                        help_text="Hex color code (e.g., #003087)",
                        max_length=20,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        help_text="Partner logo image", upload_to="partners/logos/"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the partner"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
                "ordering": ["order", "name"],
            },
        ),
    ]
