# Generated by Django 5.1.4 on 2026-06-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0003_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="partpage",
            name="hero_image_upload",
            field=models.ImageField(
                blank=True,
                help_text="Upload a hero background image",
                null=True,
                upload_to="hero/images/",
            ),
        ),
        migrations.AddField(
            model_name="partpage",
            name="hero_video_upload",
            field=models.FileField(
                blank=True,
                help_text="Upload an MP4 hero background video",
                null=True,
                upload_to="hero/videos/",
            ),
        ),
        migrations.AlterField(
            model_name="partpage",
            name="hero_image",
            field=models.CharField(
                default="/images/hero.png",
                help_text="Legacy fallback image path",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="partpage",
            name="video_url",
            field=models.CharField(
                blank=True, help_text="Legacy fallback video URL", max_length=300
            ),
        ),
    ]
