# Generated by Django 5.1.4 on 2026-06-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0004_partpage_hero_image_upload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partpage",
            name="product_image_upload",
            field=models.ImageField(
                blank=True,
                help_text="Upload a product image",
                null=True,
                upload_to="products/images/",
            ),
        ),
    ]
